# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release

variables:
- group: credenciales

steps:
- script: |
    rsync -auv -e 'sshpass -p "$(password_produccion)" ssh -o StrictHostKeyChecking=no' --chown=magotteauxtestin:magotteauxtestin  --exclude='.htaccess' --exclude='*.md' --exclude='*.yml' --exclude='.git' --exclude='.env'  --exclude='.env.example' --exclude='composer.lock' --exclude='BD' . root@45.33.42.95:/home/magotteauxtestin/public_html/
  displayName: 'Rsync a servidor de AMBIENTE'


- task: SSH@0
  inputs:
    sshEndpoint: 'AMBIENTE'
    runOptions: 'commands'
    commands: |
      cd /home/magotteauxtestin/public_html/ && composer update && php artisan migrate
    readyTimeout: '20000'
